/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dadad7',
        'outline-variant': '#c5c6ce',
        'tertiary-container': '#261a00',
        'success-verified': '#2E7D32',
        'on-tertiary-fixed': '#261a00',
        'surface-variant': '#e2e3e0',
        'secondary-container': '#fdc34d',
        'on-background': '#1a1c1b',
        'error-container': '#ffdad6',
        'on-surface': '#1a1c1b',
        'on-secondary': '#ffffff',
        'surface-bright': '#f9f9f6',
        'on-primary-fixed': '#0d1b35',
        'surface': '#f9f9f6',
        'primary-container': '#0d1b35',
        'primary-fixed': '#d8e2ff',
        'on-surface-variant': '#45474d',
        'on-secondary-fixed': '#271900',
        'tertiary-fixed-dim': '#ecc165',
        'secondary': '#7b5800',
        'outline': '#75777e',
        'error': '#ba1a1a',
        'inverse-on-surface': '#f1f1ee',
        'surface-alt': '#F0EDE8',
        'tertiary': '#010100',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#2f312f',
        'surface-container-low': '#f4f4f1',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#3a4763',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#5d4200',
        'on-tertiary-container': '#a37f2a',
        'on-secondary-container': '#715000',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'surface-container': '#eeeeeb',
        'secondary-fixed-dim': '#f7bd48',
        'secondary-fixed': '#ffdea6',
        'tertiary-fixed': '#ffdfa0',
        'on-primary-container': '#7784a3',
        'surface-tint': '#515e7c',
        'inverse-primary': '#b9c6e8',
        'surface-container-highest': '#e2e3e0',
        'primary': '#000000',
        'surface-container-high': '#e8e8e5',
        'primary-fixed-dim': '#b9c6e8',
        'error-alert': '#C62828',
        'navy-glass': 'rgba(13, 27, 53, 0.85)',
        'background': '#f9f9f6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'margin-mobile': '16px',
        'gutter': '24px',
        'margin-desktop': '40px',
        'base': '4px',
      },
      fontFamily: {
        h2: ['Montserrat', 'sans-serif'],
        'h1-mobile': ['Montserrat', 'sans-serif'],
        'data-md': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        h3: ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        h1: ['Montserrat', 'sans-serif'],
        'data-lg': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        h2: ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'h1-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'data-md': ['14px', { lineHeight: '1', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-lg': ['20px', { lineHeight: '1', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}